---
# handlers file for ansible-role-zerotier
- name: start zerotier-one
  service: 
    name: zerotier-one 
    state: started
    enabled: yes

- name: stop zerotier-one
  service: 
    name: zerotier-one
    state: stopped

- name: restart zerotier-one
  service: 
    name: zerotier-one
    state: restarted

- name: enable zerotier-one
  service: 
    name: zerotier-one
    enabled: yes